apiVersion: v1
kind: Service
metadata:
  name: rt-database
  labels:
    app: rt
spec:
  ports:
    - port: 3306
  selector:
    app: rt
    tier: database
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rt-database
  labels:
    app: rt
spec:
  selector:
    matchLabels:
      app: rt
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rt
        tier: database
    spec:
      containers:
      - image: docker.io/mariadb:10
        name: database
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_USER
          value: rt_user
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

